/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/stories`; params?: Router.UnknownInputParams; } | { pathname: `/story-builder`; params?: Router.UnknownInputParams; } | { pathname: `/tag-management`; params?: Router.UnknownInputParams; } | { pathname: `/workspace-settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownInputParams; } | { pathname: `/campaign/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/stories/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/stories`; params?: Router.UnknownOutputParams; } | { pathname: `/story-builder`; params?: Router.UnknownOutputParams; } | { pathname: `/tag-management`; params?: Router.UnknownOutputParams; } | { pathname: `/workspace-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownOutputParams; } | { pathname: `/campaign/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/stories/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/stories${`?${string}` | `#${string}` | ''}` | `/story-builder${`?${string}` | `#${string}` | ''}` | `/tag-management${`?${string}` | `#${string}` | ''}` | `/workspace-settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/callback${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/stories`; params?: Router.UnknownInputParams; } | { pathname: `/story-builder`; params?: Router.UnknownInputParams; } | { pathname: `/tag-management`; params?: Router.UnknownInputParams; } | { pathname: `/workspace-settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownInputParams; } | `/campaign/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/stories/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/campaign/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/stories/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
